
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    database-platform:
    show-sql: true
    hibernate:
#      ddl-auto: update
      hbm2ddl: auto=update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate: info
      springframework:
        security: debug